### ISSUE TITLE
Omega Proxy Extention

### ISSUE THREAD

**Issue by arshambh** [GFW-knocker/gfw_resist_HTTPS_proxy#38]
سلام من وقتی از اکستنشن مرورگر یا از بخش proxy ویندوز استفاده میکنم و توش ip و port با پروتکل http ست میکنم خطا زیر میگیرم
`redirect b'GET http to HTTPS https://detectportal.firefox.com/canonical.html
info file writed to C:\Users\Administrator\Desktop\gfw_resist_HTTPS_proxy-main\DNS_IP_traffic_info.txt
Exception in thread Thread-56 (my_upstream):
Unknown Method b''
Unknown Method b''
Traceback (most recent call last):
Exception in thread Thread-57 (my_upstream):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Administrator\Desktop\gfw_resist_HTTPS_proxy-main\pyprox_HTTPS_v3.0.py", line 407, in my_upstream
  File "c:\Users\Administrator\Desktop\gfw_resist_HTTPS_proxy-main\pyprox_HTTPS_v3.0.py", line 407, in my_upstream
    backend_sock = self.handle_client_request(client_sock)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    backend_sock = self.handle_client_request(client_sock)
  File "c:\Users\Administrator\Desktop\gfw_resist_HTTPS_proxy-main\pyprox_HTTPS_v3.0.py", line 325, in handle_client_request
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    data = client_socket.recv(16384)
  File "c:\Users\Administrator\Desktop\gfw_resist_HTTPS_proxy-main\pyprox_HTTPS_v3.0.py", line 325, in handle_client_request
           ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
    data = client_socket.recv(16384)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`

ممنون میشم راهنماییی کنید

**Comment by GFW-knocker** [comment]
احتمالا پروتکلی غیر از http ست کردید
بهتره مرورگر فایرفاکس رو تنظیم کنید 
firefox > settings > network settings > manual proxy > also use this for HTTPS
